// ---------------------- haiku drawing -------------------------------

const char haikus[][4][50] = {
    {"I can only write\n","These haikus by using my\n","Fingers to help count\n","Sally Hunter\n"},
    {"I adore all cats\n","I want to pet, scritch, boop, kiss!\n","But they want to bite\n","Sally Hunter\n"},
    {"The candy store of\n","My heart sells only gumballs\n","When you are not here\n","Sally Hunter\n"},
    {"There are a finite\n","Number of sunsets in life\n","Spend just one with me\n","Sally Hunter\n"},
    {"a year at most...\n","we pretend to watch\n","the hummingbirds\n","Tom Bierovic\n"},
    {"Mars landing\n","cardboard softens\n","the subway grate\n","Scott Mason\n"},
    {"daisies -\n","learning to live\n","in a crowd again\n","Tony Williams\n"},
    {"open meadow\n","a monarch hinges\n","on a milkweed\n","Brad Bennett\n"},
    {"blossom to blossom\n","a bee tips the fate\n","of the world\n","June Rose Dowis\n"},
    {"sand dollars\n","all that's left of\n","her summer job\n","Margaret Tau\n"},
    {"the heft\n","of a cast-iron skillet\n","autumn deepens\n","Mary Stevens\n"},
    {"evening news\n","junipers consume\n","the moon\n","Kat Lehmann\n"},
    {"whether or not\n","you come home\n","spring peepers\n","Carol Ann Palomba\n"},
    {"gibbous moon\n","she circles the baby's\n","due date\n","Marilyn Appl Walker\n"},
    {"casting off\n","all self-doubt -\n","prize trout\n","Clifford Rames\n"},
    {"ultrasound\n","the thump of a bee\n","against the window\n","Raquel D. Bailey\n"},
    {"high summer\n","the slow drift\n","of a heron's landing\n","Michael Morell\n"},
    {"downpour\n","alone together\n","with our phones\n","Paul Kulwatno\n"},
    {"dawn chorus\n","all the birds\n","he used to know\n","Jacquie Pearce\n"},
    {"frosty night...\n","the horse's breath\n","melts a star\n","Martha Magenta\n"},
    {"barn owl's cry\n","the darkness\n","pierced with wounds\n","Temple Cone\n"},
    {"it ends\n","with a text\n","april rain\n","Matthew Markworth\n"},
    {"crack house\n","even the shadows\n","have shadows\n","Roland Packer\n"},
    {"to lead a life\n","of such purpose...\n","ants in a line\n","Annette Makino\n"},
    {"sun-bleached billboard\n","the gravel road ends\n","at peaches\n","Joe McKeon\n"},
    {"flute notes\n","fluttering\n","petals\n","Brett Brady\n"},
    {"the rill's trick\n","a greenfinch moves\n","its green around\n","Alan Summers\n"},
    {"the first stroke\n","of the ink brush...\n","ravens in snow\n","Ron C. Moss\n"},
    {"evening prayer\n","the sediment\n","begins to settle\n","Jayne Miller\n"},
    {"a turnstile\n","going around by itself -\n","winter rain\n","Barry George\n"},
    {"winter solitude\n","lost in the hum\n","of my computer\n","Sam Bateman\n"},
    {"light\n","for their world\n","fireflies\n","Gary Hotham\n"},
    {"gathering dusk\n","all the colored pencils\n","back in their cup\n","Michele Root-Bernstein\n"},
    {"the dogs\n","shake it loose\n","- summer sea\n","Alison Woolpert\n"},
    {"trial separation\n","another inch of snow\n","on the gin bottles\n","Lew Watts\n"},
    {"summer holiday\n","walking the dogs\n","where they want to go\n","Corine Timmer\n"},
    {"spindrift...\n","I go where\n","the story takes me\n","Francine Banwarth\n"},
    {"drifting snowflakes\n","the police car's ascent\n","up our driveway\n","Christina Sng\n"},
    {"evening breeze\n","through the barnboards\n","final bid\n","Roland Packer\n"},
    {"our easy silence\n","every puddle\n","sky-deep\n","Annette Makino\n"},
    {"wedding invitations\n","the press and release\n","of the nib\n","Robyn Hood Black\n"},
    {"paddling through stars\n","the wake of a boat\n","long passed\n","Julie Warther\n"},
    {"pride parade\n","from behind a cloud\n","the sun comes out\n","Olivier Schopfer\n"},
    {"stone cairns\n","a faded cap drifts\n","downriver\n","Debbie Strange\n"},
    {"jasmine beyond\n","the honeycombed lattice\n","a call to prayer\n","Scott Mason\n"},
    {"sand dunes\n","by morning\n","a different dream\n","Renée Owen\n"},
    {"early morning\n","mist reunites\n","the hills\n","Kevin Goldstein-Jackson\n"},
    {"the underside of leaves\n","her back story\n","changes everything\n","Michele Root-Bernstein\n"},
    {"snow crocus\n","my grandson asks\n","if I have dreams\n","Joe McKeon\n"},
    {"county fair\n","ribbon\n","in an empty stall\n","Joe McKeon\n"},
    {"junk car\n","the hum of bees\n","beneath the hood\n","John Stevenson\n"},
    {"the Christmas\n","after we told them\n","artificial tree\n","Joe McKeon\n"},
    {"a bit of rust\n","on the Chevy's fender\n","harvest moon\n","Terri L. French\n"},
    {"forest clearing\n","a scapula\n","left for the moon\n","Scott Mason\n"},
    {"that time of year\n","moonlight fills\n","his empty chair\n","Phyllis Lee\n"},
    {"birding...\n","the unfamiliar path\n","home\n","Julie Warther\n"},
    {"winter solstice\n","the tilt\n","of her hospital bed\n","Carolyn Hall\n"},
    {"first morning\n","firecracker papers\n","wander the streets\n","Josephy Robello\n"},
    {"flies wait it out\n","under a cow's chin\n","spring shower\n","Temple Cone\n"},
    {"heartwood\n","the saw changes\n","its tune\n","Michele L. Harvey\n"},
    {"snow field\n","the earth marked\n","by fallen angels\n","Elizabeth Steinglass\n"},
    {"setting sun\n","an accordion squeezes\n","the night air\n","June Dowis\n"},
    {"no moon\n","the click of stilettos\n","on cobblestones\n","Ernest Berry\n"},
    {"flowing estuary\n","native languages\n","long gone\n","Mike Blottenberger\n"},
    {"in the hot tub\n","my eyes on her floating breasts\n","Hunters Moon\n","Neal Whitman\n"},
    {"rosebud unfolding\n","the seed packet left behind\n","in Revelations\n","Scott Mason\n"},
    {"no escaping\n","this moonlight -\n","Pompeii\n","Scott Mason\n"},
    {"river mud\n","the shape\n","of boys\n","Jayne Miller\n"},
    {"desert twilight\n","a map with many creases\n","nailed to a cross\n","Garry Gay\n"},
    {"we huddle\n","over mother's open grave -\n","lawless winter\n","Anita Curran Guenin\n"},
    {"a long bus ride\n","the prophetic language\n","of the stops\n","Michael McClintock\n"},
    {"Navajo moon\n","the coyote call\n","not a coyote\n","Garry Gay\n"},
    {"deleting words\n","from the eulogy\n","falling leaves\n","Mark Smith\n"},
    {"calla lily\n","the sound of a ladder\n","lengthening\n","Cherie Hunter Day\n"},
    {"tasting the well\n","in the water -\n","summer stars\n","Marjorie Buettner\n"},
    {"Mother's Day\n","the expiration date\n","on wildflower seeds\n","Carolyn Hall\n"},
    {"northern lights...\n","the scratchy play\n","of seventy-eights\n","Michele L. Harvey\n"},
    {"the big dipper\n","no matter where I stand\n","mountain sky\n","Michelle Schaefer\n"},
    {"summer passing\n","the yard flamingo's\n","rusty legs\n","Michelle Schaefer\n"},
    {"glint of sunlight\n","the respirator carries on\n","alone\n","Charles Trumbull\n"},
    {"All Souls Day...\n","my name called\n","from the front gate\n","Michele L. Harvey\n"},
    {"autumn\n","an empty booster seat\n","in the barber's window\n","Tish Davis, Ohio\n"},
    {"hunter's cabin\n","of the woods\n","not of it\n","Michele L. Harvey\n"},
    {"end of the walk\n","returning the crow's feather\n","where I found it\n","Margaret Chula\n"},
    {"cafe for sale -\n","outdoor tables rusting\n","into autumn\n","Adelaide B. Shaw\n"},
    {"day lilies\n","another death date added\n","to the family tree\n","Carolyn Hall\n"},
    {"The house finch\n","has a song for it,\n","morning after snow\n","Stephen Gould\n"},
    {"crescent moon\n","a bone carver sings\n","to his ancestor\n","Ron Moss\n"},
    {"close enough to touch -\n","I let the junco lead me\n","away from its nest\n","C. R. Manley\n"},
    {"Blowing leaves\n","tempt the old cat,\n","but not enough\n","Bruce England\n"},
    {"ancient mountains...\n","runners clearing hurdles\n","on the practice field\n","Michael McClintock\n"},
    {"Thanksgiving -\n","fifteen minutes\n","of mince pie\n","John Stevenson\n"},
    {"blossoms...\n","the baby's bare feet\n","pedal the air\n","Kristen Deming\n"},
    {"butterfly\n","my attention\n","attention span\n","John Stevenson\n"},
    {"one moth\n","a thousand candles\n","light the darkness\n","Garry Gay\n"},
    {"trail's end -\n","my pebble\n","settles the cairn\n","Linda Jeannette Ward\n"},
    {"family reunion -\n","some of the beached kelp\n","in knots\n","Claire Gallagher\n"},
    {"a jar of pennies\n","on the lemonade stand\n","evening cool\n","Roland Packer\n"},
    {"lightning...\n","the scarecrow's coat sleeve\n","caught in mid-wave\n","Ken Hurm\n"},
    {"summer's end\n","the hammock turned in\n","on itself\n","Marjorie Buettner\n"},
    {"Charcoal Alley -\n","children flick marbles\n","into the light\n","Ron Moss\n"},
    {"season of lights\n","the postman\n","leans to the wind\n","Ellen Compton\n"},
    {"having no thought\n","we've come to see them -\n","dogwoods in bloom\n","Michael McClintock\n"},
    {"turning tide -\n","placing intact clams\n","back in the water\n","C. R. Manley\n"},
    {"mallard pair\n","he rocks\n","on her wake\n","Alice Frampton\n"},
    {"filtering in\n","with the night air\n","a skunk's warning\n","Lois J. Funk\n"},
    {"stone in my pocket -\n","the brook cuts deeper\n","into the mountain\n","Merrill Ann Gonzales\n"},
    {"a bee chose\n","the rose I meant to pluck...\n","empty vase\n","Joan M. Murphy\n"},
    {"soba noodles...\n","the new year\n","slips in\n","Sandra Nickel\n"},
    {"hazy dusk...\n","no one bothered to plow\n","the graveyard road\n","Bruce Ross\n"},
    {"child's wake\n","the weight\n","of rain\n","Francine Banwarth\n"},
    {"a stick caught\n","on the lip of the dam\n","winter's end\n","Rick Tarquinio\n"},
    {"summer stars...\n","the old violin goes\n","to the highest bidder\n","Francine Banwarth\n"},
    {"winter drags on...\n","I squeeze the last drops\n","from a teabag\n","Kirsty Karkow\n"},
    {"distant thunder -\n","a titmouse gives one chirp\n","and falls silent\n","Origa\n"},
    {"Alzheimer's birthday\n","each slice of the cake\n","takes part of her name\n","Bill Pauly\n"},
    {"March winds\n","a decade has passed\n","by your grave\n","Marie Summers\n"},
    {"Indian summer\n","a spent salmon\n","washes ashore\n","w.f. owen\n"},
    {"after the funeral\n","whiskers still\n","in his razor\n","Becky Barnhart\n"},
    {"the page-finders\n","of my father's Daily Missal\n","losing their colors\n","Michael Fessler\n"},
    {"first buds of spring\n","I change the washer's setting\n","to delicate\n","Marjorie Buettner\n"},
    {"Among the gravestones\n","with names worn away\n","children play hide n seek\n","George Swede\n"},
    {"whalebone\n","from a beach near Savoonga -\n","winter rain\n","Billie Wilson\n"},
    {"All Saints morning\n","a path\n","of trodden leaves\n","John Stevenson\n"},
    {"cremated\n","in her favorite kimono -\n","small green plums\n","Carolyn Hall\n"},
    {"spring rain -\n","the gravedigger latches the door\n","of his backhoe\n","Timothy Russell\n"},
    {"loon calls\n","my daughter drawing circles\n","near the fire\n","Marjorie Buettner\n"},
    {"summer evening -\n","from across the meadow\n","a call to supper\n","Billie Wilson\n"},
    {"shivering on the roof\n","I rub my palms together\n","meteor shower\n","Michael Fessler\n"},
    {"ocean breeze -\n","a strand of seaweed\n","steadies the kite\n","John Thompson\n"},
    {"autumn rose -\n","even as I sketch the wind\n","more petals fall\n","Ross Figgins\n"},
    {"Humid July -\n","from the stove the smell\n","of old fires\n","Doug Hunt\n"},
    {"the wind of autumn\n","a homeless man warms himself\n","hand to mouth\n","Harvey Hess\n"},
    {"broken easel -\n","the front yard blue\n","with wildflowers\n","Kathy Lippard Cobb\n"},
    {"heat waves -\n","the hitchhiker shifts her child\n","to the other hip\n","Linda Jeannette Ward\n"},
    {"land's end -\n","sand in each bite\n","of my apple\n","Leatrice Lifshitz\n"},
    {"Indian summer\n","a fish slips through\n","the gill net\n","W. F. Owen\n"},
    {"her 18th birthday -\n","for the first time she notices\n","my silences\n","Jeanne Emrich\n"},
    {"spring sunshine\n","the climbing ivy\n","filled with sparrows\n","A. C. Missias\n"},
    {"meteor shower -\n","a gentle wave\n","wets our sandals\n","Michael Dylan Welch\n"},
    {"mountain hike\n","we drink from the beginning\n","of a great river\n","Yvonne Hardenbrook\n"},
    {"spring sun -\n","high in his arms\n","the newborn is shown\n","Tom Clausen\n"},
    {"snail -\n","to know\n","its heart beats too\n","Marian Olson\n"},
    {"lethal injection\n","unable to shut\n","the blind dog's eyes\n","LeRoy Gorman\n"},
    {"end of summer\n","the shape of his feet\n","in his sneakers\n","Peggy Heinrich\n"},
    {"Geronimo's grave\n","someone has left\n","plastic flowers\n","Linda Jeannette Ward\n"},
    {"new in town\n","the scent\n","of unknown flowers\n","Yu Chang\n"},
    {"foghorns...\n","we lower a kayak\n","into the sound\n","Christopher Herold\n"},
    {"catalog time\n","the garden begins\n","without a seed\n","Celia Stuart-Powles\n"},
    {"new butterfly...\n","folded wings\n","lean into the wind\n","Ferris Gilli\n"},
    {"morning overcast\n","a few seeds still dangle\n","from the dandelion\n","Christopher Herold\n"},
    {"break up\n","I leave behind\n","her butterfly net\n","R.A. Stefanac\n"},
    {"walking home barefoot,\n","we enter the shadow\n","of the hill\n","John Stevenson\n"},
    {"autumn evening...\n","a page of the old book\n","separates from the spine\n","Tom Tico\n"},
    {"funeral procession...\n","snowflakes blowing\n","into the headlights\n","Randy Brooks\n"},
    {"autumn evening\n","my hospital window\n","becomes a mirror\n","Zinovy Vayman\n"},
    {"storm clouds\n","the cry of a shearwater\n","circles the sky\n","Ernest Berry\n"},
    {"late into the night\n","we talk of revelations\n","moon through the pines\n","Margaret Chula\n"},
    {"the kettle whistles...\n","a blur of garden color\n","on the window\n","Christopher Herold\n"},
    {"winter beach\n","a piece of driftwood\n","charred at one end\n","John Stevenson\n"},
    {"riveredge old growth\n","a towering window\n","of stars\n","Ruth M. Yarrow\n"},
    {"Over the railroad tracks\n","the slow motion\n","of a snake\n","Gary Gay\n"},
    {"The beetle I righted\n","flies straight into\n","a cobweb\n","George Swede\n"},
    {"leaf in my palm\n","its stem extends\n","my lifeline\n","Helen Davie\n"},
    {"about the tree\n","over my small son's grave\n","- tell me\n","Susan Gaston\n"},
    {"musty smell\n","forgotten... deep\n","into the text\n","William J. Higginson\n"},
    {"that Venus!\n","leading the cupped moon\n","through every turn of the road\n","Connie Meester\n"},
    {"grabs and 'opens'\n","the fist\n","sowing seeds\n","Kohjin Sakamoto\n"},
    {"the river -\n","coming to it with nothing\n","in my hands\n","Leatrice Lifshitz\n"},
    {"deep silence\n","the orphaned nestlings\n","this third morning\n","Kay F. Anderson\n"},
    {"summer solstice -\n","the long tips of lavender\n","bent by bees\n","Jeffrey Witkin\n"},
    {"snowbound\n","coloring inside\n","the lines\n","Sandra Fuhringer\n"},
    {"the dumproad pond\n","tadpoles exit\n","a birdhouse\n","LeRoy Gorman\n"},
    {"still sun-warmed...\n","the pulled-out scarecrow\n","in my arms\n","Kohjin Sakamoto\n"},
    {"Changing the swallowtail\n","changed by it\n","the spring wind\n","vincent tripi\n"},
    {"letting the branch go\n","a shower of petals falls\n","on the old woman\n","Leatrice Lifshitz\n"},
    {"toll booth lit for Christmas\n","from my hand to hers\n","warm change\n","Michael Dylan Welch\n"},
    {"winter seclusion\n","tending all day\n","the small fire\n","Jim Kacian\n"},
    {"on the path\n","only one of us\n","touched by a falling leaf\n","Helen K. Davie\n"},
    {"winter, bedtime\n","static flickers\n","through a white sleeve\n","John Stevenson\n"},
    {"warm river -\n","up to our necks\n","in sunset\n","Ruth Yarrow\n"},
    {"beneath the ice\n","the waterfall\n","still falling\n","Jeanne Emrich\n"},
    {"Old garden chair\n","sagging with the weight\n","of a single leaf.\n","Alice Mackenzie Swaim\n"},
    {"after the stroke...\n","watching only the half of your face\n","that smiles\n","Helen K. Davie\n"},
    {"City window\n","mountains and pines\n","etched in frost\n","Peggy Heinrich\n"},
    {"Autumn deepens\n","an empty snail shell\n","explored by an ant\n","Garry Gay\n"},
    {"early morning sun\n","scattered on the table\n","several grains of salt\n","Christopher Herold\n"},
    {"snowflakes\n","no one will miss\n","melt in her hand\n","Gary Hotham\n"},
    {"bright leaves\n","blow through\n","her dream house\n","John Stevenson\n"},
    {"scattering his ashes\n","the moon\n","in bits and pieces\n","Sylvia Forges-Ryan\n"},
    {"on the river\n","of many names, one cloud\n","floating\n","Virginia Brady Young\n"},
    {"learning too late\n","he didn't like bubinga wood -\n","sun strikes the urn\n","Elizabeth Searle Lamb\n"},
    {"the war memorial -\n","migrating butterflies\n","cover the names\n","Penny Harter\n"},
    {"falling leaves\n","the house comes\n","out of the wood\n","Jim Kacian\n"},
    {"leaving you -\n","fog on either side\n","of the white heron\n","Leatrice Lifshitz\n"},
    {"Below zero\n","all curled up in the woodpile\n","the skin of a snake\n","June Moreau\n"},
    {"deep winter.\n","the armload of firewood\n","chills the kitchen\n","Carol A. Purington\n"},
    {"mourning dove calls...\n","my elderly neighbor stills\n","the sound of her hoeing\n","James Chessing\n"},
    {"August morning -\n","a window washer wiping dust\n","from his sunglasses\n","Lenard D. Moore\n"},
    {"snowmelt...\n","she enters\n","the earth on her knees\n","Bill Pauly\n"},
    {"an old woolen sweater\n","taken yarn by yarn\n","from the snowbank\n","Michael Dylan Welch\n"},
    {"a white horse\n","drinks from the acequia\n","blossoming locust\n","Elizabeth Searle Lamb\n"},
    {"sunlight shines red\n","through my father's thumb\n","on the steering wheel\n","Alyson Pou\n"},
    {"two women crying\n","one giving birth\n","the other being born\n","John Thompson\n"},
    {"Approaching the family plot...\n","my furled umbrella\n","turns into a cane.\n","vincent tripi\n"},
    {"Chernobyl victim -\n","fingers pressing the plastic\n","to his wife's caress\n","Marc Arvid White\n"},
    {"cloud shadow\n","long enough to close\n","the poppies\n","Christopher Herold\n"},
    {"The thick clang\n","of a cowbell\n","the sun deepens\n","June Moreau\n"},
    {"Roses\n","in the smaller room\n","more fragrant\n","Sydney Bougy\n"},
    {"Ninety winters\n","Spellbound\n","Again\n","Vicki Silvers\n"},
    {"silent cathedral\n","stained-glass apostles\n","dimming with dusk\n","Charles B. Dickson\n"},
    {"up the path\n","to touch that one oak\n","in last night's dream\n","R. J. Trayhern\n"},
    {"dry leaves\n","the old archer\n","curves his eyebrow\n","Jim Boyd\n"},
    {"soft rain -\n","the new grave\n","looks old\n","William Cullen, Jr.\n"},
    {"morning sneeze -\n","the guitar in the corner\n","resonates\n","Dee Evetts\n"},
    {"dusk\n","a lone car going the same way\n","as the river\n","George Swede\n"},
    {"First days of summer...\n","already the leaves gather\n","beneath the sycamores\n","Tom Tico\n"},
    {"so many ways\n","within the waterfall\n","for water to fall\n","John Thompson\n"},
    {"after the rain\n","on my vegetable patch\n","a new crop of stones\n","Dee Evetts\n"},
    {"frozen in mud\n","by the vacant shanty\n","lottery ticket\n","Joe Nutt\n"},
    {"the potter's hands\n","gently shape the vase\n","out of himself\n","Frederick Gasser\n"},
    {"Watermelon rind,\n","sitting in its own juice\n","the summer sun\n","Garry Gay\n"},
    {"figure drawing class -\n","in the model's deepest shadows\n","a stark white string\n","Lee Gurga\n"},
    {"Ebb tide...\n","a little sea\n","in the shell\n","Robert Mainone\n"},
    {"watching rain\n","pouring down... pouring down\n","just watching\n","Joan Bulger Murphy\n"},
    {"abandoned store -\n","large sign reading\n","WE NEVER CLOSE\n","Denver Stull\n"},
    {"a single strand\n","of spider silk\n","stops her\n","Dan Burke\n"},
    {"mime\n","lifting\n","fog\n","Jerry Kilbride\n"},
    {"taking time...\n","listening\n","to the grocery clerk\n","Carolyn Talmadge\n"},
    {"in the Yukon\n","sleeping with one eye shut\n","the summer night\n","Elizabeth St Jacques\n"},
    {"in soap bubbles\n","again and again\n","his face is broken\n","Bill Pauly\n"},
    {"yard sale,\n","sunlight filling\n","mason jars\n","Jerry Kilbride\n"},
    {"leaving home...\n","the smell of smoke\n","from old brick chimneys\n","Kathleen Burgy\n"},
    {"frozen pond -\n","white antlers rise\n","through the ice\n","Ross Figgins\n"},
    {"June night\n","my mother alone with\n","her cancer\n","Steven D. Dalachinsky\n"},
    {"at dinner\n","biting into the roast beef...\n","the butcher's thumb nail\n","Sister Mary Thomas Eulberg\n"},
    {"phoning the neighbors\n","their real voices\n","through the open window\n","Dee Evetts\n"},
    {"repeating the lecture\n","his eyes following\n","the window-cleaner's blade\n","Dee Evetts\n"},
    {"Tools rusting\n","Unused on the work bench\n","A faucet dripping\n","Esther Harris\n"},
    {"full moon\n","peering into\n","the half-built house\n","H. F. Noyes\n"},
    {"dusk\n","drawing the pond's depth\n","to the surface\n","Donald E. McLeod\n"},
    {"old woman, wrapping\n","her cat's gifts\n","- centering the bows\n","Carol Montgomery\n"},
    {"on the way to work\n","a hot air balloon\n","up in the mist\n","Lynn G. Moore\n"},
    {"this heat;\n","the dog's tail\n","the only breeze\n","Denver Stull\n"},
    {"light\n","up under the gull's wing\n","sunrise\n","Ruth M. Yarrow\n"},
    {"second husband\n","painting the fence\n","the same green\n","Carol Montgomery\n"},
    {"such coolness\n","the snail stretches\n","its neck\n","Clark Strand\n"},
    {"the one legged bird\n","that deep bend before\n","taking off\n","David E. LeCount\n"},
    {"bird song\n","lost\n","in bird song\n","Peggy Willis Lyles\n"},
    {"walking in on her\n","dead eyes reflecting\n","snowfall\n","Bill Pauly\n"},
    {"in the sea\n","the fireworks\n","rising\n","Rebecca Rust\n"},
    {"bird feeder untouched...\n","\n","alone again\n","Ruby Spriggs\n"},
    {"circling each thigh\n","cool\n","of the night river\n","Ruth M. Yarrow\n"},
    {"small child\n","afraid to throw away\n","his Church Bulletin\n","Carol Montgomery\n"},
    {"in utter stillness\n","the incense\n","changes direction\n","Stephen Hobson\n"},
    {"early spring sun -\n","the spinster combs out her hair\n","for nesting birds\n","David E. LeCount\n"},
    {"canyon\n","at the very edge\n","riversound\n","Ruth Yarrow\n"},
    {"Out of its slipper\n","her bare foot talking\n","under the table\n","Robert F. Mainone\n"},
    {"Burial prayers\n","grandson playing hide and seek\n","behind the stones\n","David Elliott\n"},
    {"My father's hammer\n","warm again\n","in my hand\n","Dorothy McLaughlin\n"},
    {"under trees and sky\n","the baby studies\n","her hands\n","Margarita Mondrus Engle\n"},
    {"migrating geese -\n","once there was so much\n","to say\n","Adele Kenny\n"},
    {"sound of her voice\n","carrying eggs\n","across the ice\n","Bill Pauly\n"},
    {"moving\n","with the clock tower's shadow\n","the flower lady\n","Alexis K. Rotella\n"},
    {"heart drawn in dust\n","by the old Indian...\n","rain\n","Bill Pauly\n"},
    {"whispered dusk -\n","a fox picks its way\n","across the ice\n","Ross Figgins\n"},
    {"mist\n","lifting\n","the loon's cry\n","Ruth M. Yarrow\n"},
    {"snowman's eye\n","sinking in\n","the spring rain\n","Ruth M. Yarrow\n"},
    {"Autumn afternoon\n","I stand on the shadow\n","of the sparrow\n","Joyce Walker Currier\n"},
    {"ten below zero\n","man and boy walk through their breath\n","to read old tombstones\n","Bill Pauly\n"},
    {"hot wind\n","the roadrunner's beak\n","opens and closes\n","Margarita Mondrus Engle\n"},
    {"Blackbirds descend\n","through the floaters\n","in this eye\n","Charles L. Cutler\n"},
    {"the old man\n","closes the shadow\n","in his hand\n","Darold D. Braida\n"},
    {"spring drizzle\n","rounding the thorn\n","a drop of light\n","Ruth M. Yarrow\n"},
    {"horizon\n","wild swan drifting through\n","the woman's body\n","Raymond Roseliep\n"},
    {"deserted wharf\n","the mime bows\n","to the moon\n","Chuck Brickley\n"},
    {"a spider's web\n","across the windharp\n","the silence\n","Elizabeth Searle Lamb\n"},
    {"under the back steps\n","catfish still flop in the pail -\n","the long August night\n","Rita Z. Mazur\n"},
    {"horns fold\n","at my shadow's touch;\n","brown slug\n","Darold D. Braida\n"},
    {"early April rain\n","that woman fills every jar,\n","seals them forever\n","Sister Mary Thomas Eulberg\n"},
    {"dead mynah bird...\n","with each passing car\n","its wing flaps\n","Darold D. Braida\n"},
    {"Picking cotton -\n","the memory\n","of birdtracks in the snow\n","Edward P. Willey\n"},
    {"Old tea bag;\n","tints the moon\n","slightly\n","Garry Gay\n"},
    {"blackened walnut\n","left unopened -\n","winter solstice\n","David E. Evans\n"},
    {"Distant woodchopper\n","inside the cabin\n","axbite echoes\n","Thelma Murphy\n"},
    {"The grey cranes at dusk -\n","bending in a line along\n","the crooked fenceposts\n","Richard Bodner\n"},
    {"checking for water\n","the woman finds a full moon\n","trapped in the cistern\n","L.A. Davidson\n"},
    {"Old woman,\n","rain in the eye\n","of her needle\n","Bill Pauly\n"},
    {"The path shorter now,\n","underfoot the crumbling leaves;\n","the child runs ahead\n","Gloria Buckner\n"},
    {"fields of snow\n","not only moonlight\n","but the moon\n","Robert F. Mainone\n"},
    {"cold morning sea -\n","an old man towels\n","himself in the sunlight\n","Chuck Brickley\n"},
    {"fields of corn stretching\n","as far as the eye can see\n","within a lost child\n","Sister Mary Thomas Eulberg\n"},
    {"crossing the bright sky\n","of a near-sighted swimmer,\n","the song of a bird\n","L.A. Davidson\n"},
    {"and yet\n","perishable is flesh -\n","a mountain plum\n","Furuta Soichi\n"},
    {"what thing cries out\n","deep inside us\n","cooking the turtle?\n","Bill Pauly\n"},
    {"Lights out\n","... the firefly\n","inside\n","Peggy Willis Lyles\n"},
    {"the wind\n","somewhere else -\n","bird tracks in a light snow\n","Gary Hotham\n"},
    {"apples cooking\n","in the aroma\n","pictures of my mother canning\n","Sister Mary Thomas Eulberg\n"},
    {"Dawn\n","another parting\n","with the moon\n","Stephen Gould\n"},
    {"the child\n","points at the moon\n","and says, 'bird'\n","James O'Neil\n"},
    {"one seagull\n","on a shaft of air;\n","dawn\n","Darold D. Braida\n"},
    {"Lean man\n","Carving\n","The tree's dream.\n","Kirsten Stromberg\n"},
    {"from behind me\n","the shadow of the ticket-taker\n","comes down the aisle\n","Cor van den Heuvel\n"},
    {"Walking to Work\n","Pages lap at your feet\n","The quick eye holds up the news to the day\n","Michael O'Brien\n"},
    {"Part of a dog\n","walking by upside down\n","in the roadside puddle\n","Tal Streeter\n"},
    {"Where the ripple was\n","the fisherman casts his line;\n","another ripple\n","Garry Gay\n"},
    {"Quiet strokes\n","of night swimmer the slap\n","of beaver tails...\n","Virginia Brady Young\n"},
    {"never expecting\n","the lilies in November\n","nor the small coffin\n","Raymond Roseliep\n"},
    {"the room's smallness\n","fills with light\n","this morning of snow\n","Michael McClintock\n"},
    {"The way of the conch -\n","blueing in the sea, and\n","echoing in the wind\n","Joyce Walker Currier\n"},
    {"leaving\n","all the morning glories\n"," closed\n","Elizabeth Searle Lamb\n"},
    {"Old frog\n","up to his ears\n","in moonlight\n","Robert F. Mainone\n"},
    {"reaching into sky\n","the girl breaks the wish -\n","bone of geese\n","Raymond Roseliep\n"},
    {"in a dark bag\n","onions\n","sprouting\n","Jennifer Virgil\n"},
    {"still lake -\n","a hawk makes off\n","with its image\n","R.E.T. Johnson\n"},
    {"skiers!\n","standing\n","on the wind\n","Larry E. Martin\n"}
};

const int nHaikus = 316;
int hptr = 0;                 // index into that list
const int haikuFrames = 600;  // how many frames to show each haiku for

// Haiku draw list
char haiku1Str[50];             //haikus get copied into these
char haiku2Str[50];
char haiku3Str[50];
char poetStr[50];
char spacesStr[] = "    - ";

struct item haikuList[] = {
  {ItemType::text,10,0,haiku1Str,  0,0},   // haiku display is centered, as is everything
  {ItemType::text,10,0,haiku2Str,  0,0},
  {ItemType::text,10,0,haiku3Str,  0,0},
  {ItemType::text,6,0,BlankLn,    0,0},
  {ItemType::text,6,0,spacesStr,  0,0},    // poet's name is offset to the right
  {ItemType::text,6,0,poetStr,    0,0},
  {ItemType::listend,0,0,BlankLn,0,0}
};

void doHaiku(void)
{
  hptr = random(nHaikus);
  strcpy(haiku1Str, haikus[hptr][0]);
  strcpy(haiku2Str, haikus[hptr][1]);
  strcpy(haiku3Str, haikus[hptr][2]);
  strcpy(poetStr,   haikus[hptr][3]);
}
